const TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_ADMIN_STATUS: "SET_ADMIN_STATUS",
  EMAIL_SIGN_IN: "EMAIL_SIGN_IN",
  GOOGLE_SIGN_IN: "GOOGLE_SIGN_IN",
  LOG_OUT: "LOG_OUT",
  FACEBOOK_SIGN_IN: "FACEBOOK_SIGN_IN",
  GET_ERRORS: "GET_ERRORS",
  SET_ERRORS: "SET_ERRORS",
  SET_RESULTS: "SET_RESULTS",
  SET_CENTER: "SET_CENTER",
  SET_ZOOM: "SET_ZOOM",
  GET_BUSINESS_PROFILE: "GET_BUSINESS_PROFILE",
  SET_BUSINESS_PROFILE: "SET_BUSINESS_PROFILE",
  UPDATE_BUSINESS_PROFILE: "UPDATE_BUSINESS_PROFILE",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  CLEAR_USER_PROFILE: "CLEAR_USER_PROFILE",
  SET_CURRENT_PATH: "SET_CURRENT_PATH",
  SET_APP_THEME: "SET_APP_THEME",
  SET_LOCAL: "SET_LOCAL"
}

export default TYPES;